extends GutTest
## POI pipeline: every authored building validates (route, loot room, sleepers, footprint,
## budget) and builds into a node tree; layout compilation details (walls, openings, stairs).


func _ignore_unknown_props(errors: PackedStringArray) -> PackedStringArray:
	# Props are generated by the asset pipeline's prop families; until they are merged the ids may
	# be missing from content. Everything else must be clean.
	var out: PackedStringArray = []
	for e: String in errors:
		if not e.contains("prop '"):
			out.append(e)
	return out


func test_every_poi_validates() -> void:
	var defs: Array = Content.all(&"poi")
	if defs.is_empty():
		pending("no POIs authored yet")
		return
	for d: PoiDef in defs:
		var v: PoiValidator = PoiValidator.validate(d)
		assert_eq(_ignore_unknown_props(v.errors), PackedStringArray(), "%s validates" % d.id)
		assert_gt(v.paths.size(), 0, "%s has a walkable route" % d.id)


func test_every_poi_builds() -> void:
	for d: PoiDef in Content.all(&"poi"):
		var layout := PoiLayout.compile(d)
		var inst: PoiInstance = PoiBuilder.build(layout, StringName("test/%s" % d.id))
		assert_not_null(inst.shell, "%s has a collision shell" % d.id)
		assert_gt(inst.shell.get_child_count(), 10, "%s shell has shapes" % d.id)
		var mm: int = 0
		for c: Node in inst.get_children():
			if c is MultiMeshInstance3D:
				mm += 1
		assert_gt(mm, 3, "%s batches kit pieces" % d.id)
		inst.free()


func _def(layout: Dictionary, extra: Dictionary = {}) -> PoiDef:
	var raw: Dictionary = {"id": "t", "name": "T", "tier": 1, "footprint": [12, 12], "levels": layout.get("levels", [])}
	raw.merge(layout, true)
	raw.merge(extra, true)
	var d := PoiDef.new()
	var errs: PackedStringArray = d.parse(raw, &"poi", "test")
	assert_eq(errs, PackedStringArray())
	return d


func test_walls_follow_room_boundaries() -> void:
	var d: PoiDef = _def({"levels": [{"level": 0, "plan": ["AAB", "AAB"], "rooms": {"A": {}, "B": {}}}]})
	var l := PoiLayout.compile(d)
	# Perimeter 3+3+2+2 = 10 edges plus 2 between A and B.
	assert_eq(l.walls.size(), 12)
	assert_true(l.walls.has(PoiLayout.edge_key(0, "v", Vector2i(2, 0))), "A|B wall")
	var w: Dictionary = l.walls[PoiLayout.edge_key(0, "v", Vector2i(2, 0))]
	assert_eq(w["a"], "B")
	assert_eq(w["b"], "A")
	assert_false(w["exterior"])


func test_open_to_removes_the_wall() -> void:
	var d: PoiDef = _def({"levels": [{"level": 0, "plan": ["AB"], "rooms": {"A": {"open_to": "B"}, "B": {}}}]})
	assert_false(PoiLayout.compile(d).walls.has(PoiLayout.edge_key(0, "v", Vector2i(1, 0))))


func test_locked_door_needs_its_key_and_bolt_opens_from_inside() -> void:
	var base: Dictionary = {
		"levels": [{"level": 0, "plan": ["AAB"], "rooms": {"A": {}, "B": {}}}],
		"openings": [
			{"id": "front", "at": [0, 0], "side": "S", "type": "door", "state": "closed"},
			{"id": "inner", "at": [2, 0], "side": "W", "type": "door", "state": "locked", "key": "pharmacy_key"},
			{"id": "bolt", "at": [2, 0], "side": "E", "type": "door", "state": "locked_inside"}],
		"props": [],
		"route": [{"at": [0, 2]}, {"at": [2, 0]}, {"at": [4, 0]}],
		"loot_room": {}}
	var v: PoiValidator = PoiValidator.validate(_def(base))
	assert_true(v.errors.size() > 0, "no key: the inner room is unreachable")
	base["pickups"] = [{"id": "k", "item": "pharmacy_key", "at": [1, 0]}]
	var v2: PoiValidator = PoiValidator.validate(_def(base))
	assert_eq(v2.errors, PackedStringArray(), "key in reach: route completes and the bolt lets us out")


func test_stairs_connect_levels() -> void:
	var d: PoiDef = _def({
		"levels": [
			{"level": 0, "plan": ["AAAAAA"], "rooms": {"A": {}}},
			{"level": 1, "plan": ["BBBBBB"], "rooms": {"B": {}}}],
		"openings": [{"id": "door", "at": [5, 0], "side": "E", "type": "door"}],
		"stairs": [{"level": 0, "at": [4, 0], "dir": "W"}],
		"route": [{"at": [7, 0]}, {"at": [0, 0], "level": 1}]})
	var v: PoiValidator = PoiValidator.validate(d)
	assert_eq(v.errors, PackedStringArray())
	var l: PoiLayout = v.layout
	assert_eq(l.stairs[0]["landing"], Vector2i(0, 0))
	assert_true(l.stairwell_cells(1).has(Vector2i(2, 0)), "upper floor opened over the flight")
